fix indentation of steps

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -53,23 +53,24 @@ jobs:
       fail-fast: true
       matrix:
         version: [ 2.01, 2.02, 2.03 ]
-        steps:
-          - uses: actions/checkout@v3
-          - name: 'Trigger update of Validator Codelists repository for version-${{ matrix.version }}'
-            run: |
-              HTTP_CODE=$(curl --write-out "%{http_code}\n" \
-              -H 'Accept: application/vnd.github.everest-preview+json' \
-              -H 'Authorization: Bearer ${{ secrets.IATI_BOT_PAT }}' \
-              -X POST https://api.github.com/repos/IATI/IATI-Validator-Codelists/actions/workflows/push-CI.yml/dispatches \
-              --data '{"ref": "version-${{ matrix.version }}", "inputs": { "repo": "'"$GITHUB_REPOSITORY"'", "sha": "'"$GITHUB_SHA"'"}}' \
-              --output curl_out.txt \
-              --silent )
-              echo $HTTP_CODE
-              if [[ $HTTP_CODE != '204' ]] ; then
-                echo "Reponse is not 204, check error logs"
-                cat curl_out.txt
-                exit 1
-              fi
+    steps:
+      - uses: actions/checkout@v3
+      
+      - name: 'Trigger update of Validator Codelists repository for version-${{ matrix.version }}'
+        run: |
+          HTTP_CODE=$(curl --write-out "%{http_code}\n" \
+          -H 'Accept: application/vnd.github.everest-preview+json' \
+          -H 'Authorization: Bearer ${{ secrets.IATI_BOT_PAT }}' \
+          -X POST https://api.github.com/repos/IATI/IATI-Validator-Codelists/actions/workflows/push-CI.yml/dispatches \
+          --data '{"ref": "version-${{ matrix.version }}", "inputs": { "repo": "'"$GITHUB_REPOSITORY"'", "sha": "'"$GITHUB_SHA"'"}}' \
+          --output curl_out.txt \
+          --silent )
+          echo $HTTP_CODE
+          if [[ $HTTP_CODE != '204' ]] ; then
+            echo "Reponse is not 204, check error logs"
+            cat curl_out.txt
+            exit 1
+          fi
 
   automerge:
     needs: build
